#!/bin/bash

# Script untuk setup semua models dengan relationships
# File ini akan membantu Anda melengkapi models yang tersisa

echo "📝 Daftar Models yang perlu dilengkapi:"
echo ""
echo "✅ Sudah selesai:"
echo "  - User"
echo "  - Program"  
echo "  - Student"
echo "  - Lecturer"
echo "  - Course"
echo "  - CourseSchedule"
echo ""
echo "⏳ Masih perlu dilengkapi:"
echo "  - CourseEnrollment"
echo "  - Quiz"
echo "  - QuizQuestion"
echo "  - StudentQuizAttempt"
echo "  - LearningOutcome"
echo "  - FinalProject"
echo "  - FinalProjectSupervisor"
echo "  - FinalProjectSeminar"
echo "  - AcademicAdvising"
echo "  - AdvisingSchedule"
echo "  - AdvisingBooking"
echo "  - Budget"
echo "  - ActivityPlan"
echo "  - BudgetProposal"
echo "  - BudgetApproval"
echo "  - Transaction"
echo "  - AccountabilityReport"
echo ""
echo "💡 Silakan edit models di folder app/Models/"
